/**
 * Icon Mapping: FontAwesome → Lucide React
 * 
 * This file provides a lookup table to replace all FontAwesome icons
 * with their Lucide-React equivalents.
 * 
 * Usage:
 * import { IconMap } from '@/lib/icon-mapping';
 * const Icon = IconMap['fa-chart-line'];
 * <Icon className="w-4 h-4" />
 */

import {
  LineChart,
  LayoutDashboard,
  Users,
  Store,
  Briefcase,
  MessageSquare,
  Bell,
  Settings,
  CreditCard,
  BarChart3,
  PieChart,
  Activity,
  TrendingUp,
  TrendingDown,
  DollarSign,
  Wallet,
  Receipt,
  FileText,
  FileCheck,
  CheckCircle,
  XCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  Search,
  Plus,
  Minus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Shield,
  ShieldCheck,
  ShieldAlert,
  User,
  UserPlus,
  UserMinus,
  UserCheck,
  UsersRound,
  Building2,
  Building,
  MapPin,
  Phone,
  Mail,
  Calendar,
  Clock,
  Timer,
  History,
  RefreshCw,
  RotateCcw,
  Download,
  Upload,
  ExternalLink,
  Link,
  Copy,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Menu,
  X,
  MoreHorizontal,
  MoreVertical,
  Filter,
  SlidersHorizontal,
  SortAsc,
  SortDesc,
  Grid3X3,
  List,
  Columns,
  Maximize2,
  Minimize2,
  LogOut,
  LogIn,
  Home,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Flag,
  FlagTriangle,
  Zap,
  Bolt,
  Lightbulb,
  HelpCircle,
  QuestionMark,
  BookOpen,
  GraduationCap,
  Award,
  BadgeCheck,
  Crown,
  Gem,
  Package,
  Box,
  Truck,
  ShoppingCart,
  ShoppingBag,
  Tag,
  Tags,
  Percent,
  Gift,
  Ticket,
  Receipt as ReceiptIcon,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  FileBarChart,
  FileSpreadsheet,
  Printer,
  Share2,
  Send,
  MailOpen,
  Inbox,
  Archive,
  Trash,
  Folder,
  FolderOpen,
  Database,
  Server,
  Cloud,
  Wifi,
  WifiOff,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Cpu,
  HardDrive,
  Disc,
  Save,
  Image,
  Images,
  Video,
  Music,
  Mic,
  MicOff,
  Headphones,
  Volume2,
  VolumeX,
  Play,
  Pause,
  StopCircle,
  SkipForward,
  SkipBack,
  Sun,
  Moon,
  MonitorDot,
  Layout,
  LayoutTemplate,
  PanelsTopLeft,
  PanelLeft,
  PanelRight,
  Sidebar,
  Columns as ColumnsIcon,
  GripVertical,
  Target,
  Crosshair,
  Focus,
  Scan,
  ScanLine,
  SearchSlash,
  Command,
  Keyboard,
  MousePointer,
  MousePointer2,
  Move,
  MoveVertical,
  MoveHorizontal,
  Maximize,
  Minimize,
  Expand,
  Compress,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Star as StarIcon,
  Sparkles,
  Wand2,
  Brush,
  Palette,
  Paintbrush,
  PenTool,
  Pencil,
  Eraser,
  Scissors,
  Ruler,
  Compass,
  Navigation,
  Map,
  Globe,
  Globe2,
  Languages,
  Translate,
  Hash,
  AtSign,
  Hash as HashIcon,
  Type,
  Text,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Code,
  Code2,
  Terminal,
  Braces,
  Parentheses,
  Brackets,
  Quote,
  List as ListIcon,
  ListOrdered,
  ListChecks,
  Table,
  Table2,
  Grid,
  LayoutGrid,
  LayoutList,
  Columns2,
  Rows3,
  FlipHorizontal,
  FlipVertical,
  Rotate3d,
  Axis3d,
  Box as BoxIcon,
  BoxSelect,
  SquareDashedMousePointer,
  MousePointerClick,
  Pointer,
  Hand,
  HandMetal,
  Fingerprint,
  ScanFace,
  ScanEye,
  ScanSearch,
  FileSearch,
  FileJson,
  FileCode,
  FileType,
  FileDigit,
  FileKey,
  FileLock,
  FileWarning,
  FileX,
  FileCheck2,
  FilePlus,
  FileMinus,
  FileEdit,
  FileSignature,
  Files,
  FolderTree,
  FolderGit,
  FolderKanban,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Gitlab,
  Chrome,
  Globe as GlobeIcon,
  Wifi as WifiIcon,
  Ethernet,
  Network,
  Share,
  Link2,
  Unlink,
  Paperclip,
  Attachment,
  Pin,
  PinOff,
  Bookmark,
  BookMarked,
  Library,
  Newspaper,
  Radio,
  Tv,
  Cast,
  Airplay,
  Bluetooth,
  BluetoothOff,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BatteryWarning,
  Plug,
  PlugZap,
  Power,
  PowerOff,
  Moon as MoonIcon,
  Sunrise,
  Sunset,
  Sun as SunIcon,
  Cloud as CloudIcon,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudFog,
  CloudSun,
  CloudMoon,
  CloudDrizzle,
  Thermometer,
  Droplets,
  Droplet,
  Wind,
  Umbrella,
  Snowflake,
  Flame,
  FireExtinguisher,
  Anchor,
  Anchor as AnchorIcon,
  Ship,
  Plane,
  PlaneTakeoff,
  PlaneLanding,
  Car,
  Truck as TruckIcon,
  Bus,
  Train,
  TrainFront,
  Bike,
  Footprints,
  PersonStanding,
  Accessibility,
  Eye as EyeIcon,
  Glasses,
  Sunglasses,
  Contact,
  Contact2,
  Users as UsersIcon,
  UserCog,
  UserX,
  Users2,
  UsersRound as UsersRoundIcon,
  UserCircle,
  UserSquare,
  UserRound,
  Crown as CrownIcon,
  Award as AwardIcon,
  Medal,
  Trophy,
  ThumbsUp as ThumbsUpIcon,
  ThumbsDown as ThumbsDownIcon,
  HeartHandshake,
  Handshake,
  HandHelping,
  HelpingHand,
  Rocket,
  Zap as ZapIcon,
  ZapOff,
  Flashlight,
  FlashlightOff,
  Lamp,
  LampCeiling,
  LampDesk,
  LampFloor,
  LampWallDown,
  LampWallUp,
  Lightbulb as LightbulbIcon,
  LightbulbOff,
  CandlestickChart,
  BarChart,
  BarChart2,
  BarChart3 as BarChart3Icon,
  BarChart4,
  LineChart as LineChartIcon,
  PieChart as PieChartIcon,
  AreaChart,
  Radar,
  ScatterChart,
  ChartBar,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChartScatter,
  ChartArea,
  ChartGantt,
  ChartCandlestick,
  ChartNetwork,
  ChartNoAxesColumn,
  ChartNoAxesCombined,
  Activity as ActivityIcon,
  HeartPulse,
  HeartCrack,
  Stethoscope,
  Thermometer as ThermometerIcon,
  Pill,
  Briefcase as BriefcaseIcon,
  BriefcaseMedical,
  Syringe,
  Bandage,
  ScanLine as ScanLineIcon,
  Scan,
  ScanFace as ScanFaceIcon,
  ScanEye as ScanEyeIcon,
  ScanSearch as ScanSearchIcon,
  Fingerprint as FingerprintIcon,
  Touchpad,
  TouchpadOff,
  Trackpad,
  Keyboard as KeyboardIcon,
  KeyboardOff,
  Mouse,
  MouseOff,
  Cable,
  CircuitBoard,
  Component,
  Cpu as CpuIcon,
  Database as DatabaseIcon,
  DatabaseBackup,
  DatabaseZap,
  HardDrive as HardDriveIcon,
  HardDriveDownload,
  HardDriveUpload,
  Disc as DiscIcon,
  Disc2,
  Disc3,
  DiscAlbum,
  Album,
  CaseSensitive,
  CaseUpper,
  CaseLower,
  AArrowUp,
  AArrowDown,
} from 'lucide-react';

// ========================================
// ICON MAPPING TABLE
// ========================================

export const IconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  // Navigation
  'fa-home': Home,
  'fa-dashboard': LayoutDashboard,
  'fa-chart-line': LineChart,
  'fa-chart-bar': BarChart3,
  'fa-chart-pie': PieChart,
  'fa-users': Users,
  'fa-store': Store,
  'fa-briefcase': Briefcase,
  'fa-comments': MessageSquare,
  'fa-bell': Bell,
  'fa-cog': Settings,
  'fa-gear': Settings,
  'fa-credit-card': CreditCard,
  'fa-wallet': Wallet,
  'fa-receipt': Receipt,
  'fa-file-invoice': Receipt,
  'fa-file-alt': FileText,
  'fa-file-text': FileText,
  
  // Status
  'fa-check': Check,
  'fa-check-circle': CheckCircle,
  'fa-times': X,
  'fa-times-circle': XCircle,
  'fa-exclamation-circle': AlertCircle,
  'fa-exclamation-triangle': AlertTriangle,
  'fa-info-circle': Info,
  'fa-question-circle': HelpCircle,
  
  // Actions
  'fa-search': Search,
  'fa-plus': Plus,
  'fa-minus': Minus,
  'fa-edit': Edit,
  'fa-pencil': Pencil,
  'fa-trash': Trash2,
  'fa-trash-alt': Trash2,
  'fa-eye': Eye,
  'fa-eye-slash': EyeOff,
  'fa-lock': Lock,
  'fa-unlock': Unlock,
  'fa-key': Key,
  'fa-shield': Shield,
  'fa-shield-alt': ShieldCheck,
  
  // User Management
  'fa-user': User,
  'fa-user-plus': UserPlus,
  'fa-user-minus': UserMinus,
  'fa-user-check': UserCheck,
  'fa-users-cog': UserCog,
  'fa-building': Building,
  'fa-building-o': Building2,
  
  // Communication
  'fa-envelope': Mail,
  'fa-envelope-open': MailOpen,
  'fa-phone': Phone,
  'fa-map-marker': MapPin,
  'fa-map-marker-alt': MapPin,
  
  // Time
  'fa-calendar': Calendar,
  'fa-clock': Clock,
  'fa-history': History,
  'fa-redo': RefreshCw,
  'fa-undo': RotateCcw,
  
  // File Operations
  'fa-download': Download,
  'fa-upload': Upload,
  'fa-external-link': ExternalLink,
  'fa-link': Link,
  'fa-unlink': Unlink,
  'fa-copy': Copy,
  'fa-clone': Copy,
  
  // Arrows
  'fa-chevron-down': ChevronDown,
  'fa-chevron-up': ChevronUp,
  'fa-chevron-left': ChevronLeft,
  'fa-chevron-right': ChevronRight,
  'fa-arrow-left': ArrowLeft,
  'fa-arrow-right': ArrowRight,
  'fa-arrow-up': ArrowUp,
  'fa-arrow-down': ArrowDown,
  
  // Menu
  'fa-bars': Menu,
  'fa-ellipsis-h': MoreHorizontal,
  'fa-ellipsis-v': MoreVertical,
  
  // Sort/Filter
  'fa-filter': Filter,
  'fa-sliders': SlidersHorizontal,
  'fa-sort': SortAsc,
  'fa-sort-up': SortAsc,
  'fa-sort-down': SortDesc,
  'fa-th': Grid3X3,
  'fa-list': List,
  'fa-columns': Columns,
  
  // Window
  'fa-expand': Maximize2,
  'fa-compress': Minimize2,
  'fa-sign-out': LogOut,
  'fa-sign-in': LogIn,
  
  // Ratings
  'fa-star': Star,
  'fa-heart': Heart,
  'fa-thumbs-up': ThumbsUp,
  'fa-thumbs-down': ThumbsDown,
  
  // Alerts
  'fa-flag': Flag,
  'fa-bolt': Zap,
  'fa-lightbulb': Lightbulb,
  'fa-question': QuestionMark,
  
  // Documentation
  'fa-book': BookOpen,
  'fa-graduation-cap': GraduationCap,
  'fa-certificate': Award,
  'fa-award': Award,
  'fa-check-square': BadgeCheck,
  'fa-crown': Crown,
  
  // Commerce
  'fa-box': Package,
  'fa-truck': Truck,
  'fa-shopping-cart': ShoppingCart,
  'fa-shopping-bag': ShoppingBag,
  'fa-tag': Tag,
  'fa-tags': Tags,
  'fa-percent': Percent,
  'fa-gift': Gift,
  'fa-ticket': Ticket,
  
  // Tasks
  'fa-clipboard': Clipboard,
  'fa-clipboard-check': ClipboardCheck,
  'fa-clipboard-list': ClipboardList,
  'fa-tasks': ListChecks,
  
  // Analytics
  'fa-chart': BarChart3,
  'fa-chart-area': AreaChart,
  'fa-chart-network': Activity,
  'fa-trend-up': TrendingUp,
  'fa-trend-down': TrendingDown,
  'fa-activity': Activity,
  'fa-dollar-sign': DollarSign,
  
  // System
  'fa-database': Database,
  'fa-server': Server,
  'fa-cloud': Cloud,
  'fa-wifi': Wifi,
  'fa-desktop': Monitor,
  'fa-mobile': Smartphone,
  'fa-tablet': Tablet,
  'fa-laptop': Laptop,
  
  // Images
  'fa-image': Image,
  'fa-images': Images,
  'fa-video': Video,
  'fa-play': Play,
  'fa-pause': Pause,
  
  // Theme
  'fa-sun': Sun,
  'fa-moon': Moon,
  'fa-adjust': Sun,
  
  // Grid/Layout
  'fa-th-large': LayoutGrid,
  'fa-th-list': LayoutList,
  'fa-columns': Columns2,
  
  // Misc
  'fa-bullseye': Target,
  'fa-crosshairs': Crosshair,
  'fa-terminal': Terminal,
  'fa-code': Code,
  'fa-hashtag': Hash,
  'fa-at': AtSign,
  'fa-print': Printer,
  'fa-share': Share2,
  'fa-paper-plane': Send,
  'fa-inbox': Inbox,
  'fa-archive': Archive,
  'fa-folder': Folder,
  'fa-folder-open': FolderOpen,
};

// ========================================
// HELPER FUNCTIONS
// ========================================

/**
 * Get Lucide icon by FontAwesome name
 */
export function getIcon(faName: string): React.ComponentType<{ className?: string }> | undefined {
  return IconMap[faName];
}

/**
 * Check if icon exists in mapping
 */
export function hasIcon(faName: string): boolean {
  return faName in IconMap;
}

/**
 * Get all available icon names
 */
export function getIconNames(): string[] {
  return Object.keys(IconMap);
}

// Common dashboard icon sets
export const DashboardIcons = {
  // Super Admin
  admin: {
    overview: LayoutDashboard,
    users: Users,
    vendors: Store,
    finance: DollarSign,
    disputes: AlertTriangle,
    analytics: BarChart3,
    settings: Settings,
    audit: ClipboardList,
    killSwitch: Power,
  },
  // Vendor
  vendor: {
    dashboard: LayoutDashboard,
    leads: Target,
    quotes: FileText,
    messages: MessageSquare,
    earnings: DollarSign,
    reviews: Star,
    profile: User,
    settings: Settings,
    billing: CreditCard,
  },
  // User
  user: {
    dashboard: LayoutDashboard,
    jobs: Briefcase,
    quotes: FileText,
    messages: MessageSquare,
    saved: Heart,
    notifications: Bell,
    billing: CreditCard,
    settings: Settings,
  },
};
